services:

  kafka:
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_MODE_ENABLED: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true" 

  task-service:
    build: ./task-service
    environment:
      GRPC_PORT: 50051
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: notifications
    ports:
      - "50051:50051"
    depends_on:
      - kafka


  user-service:
    build: ./user-service
    environment:
      PORT: 8082
      TASK_SERVICE_ADDR: "task-service:50051"
    ports:
      - "8082:8082"
    depends_on:
      - task-service


  notification-service:
    build: ./notification-service
    environment:
      PORT: 8083
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: notifications
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - task-service